import os

# Times
SECOND = 1
MINUTE = 60 * SECOND
HOUR   = 60 * MINUTE
DAY    = 24 * HOUR
WEEK   = 7 * DAY
YEAR   = 365 * DAY

# Couchbase
COUCHBASE_BASE_URL = os.environ['COUCHBASE_BASE_URL']

# Buckets
PODCASTS_BUCKET              = os.environ['PODCASTS_BUCKET']
PODCASTS_BUCKET_PASSWORD     = os.environ['PODCASTS_BUCKET_PASSWORD']
NEW_PODCASTS_BUCKET          = os.environ['NEW_PODCASTS_BUCKET']
NEW_PODCASTS_BUCKET_PASSWORD = os.environ['NEW_PODCASTS_BUCKET_PASSWORD']

PODCASTS_BUCKET_URL = '{}/{}'.format(COUCHBASE_BASE_URL, PODCASTS_BUCKET)
NEW_PODCASTS_BUCKET_URL = '{}/{}'.format(COUCHBASE_BASE_URL, NEW_PODCASTS_BUCKET)

# Logging
LOG_FILE = 'log'
BASE_DIR = 'csv'
LOGGER   = 'podcatch'

# Series Updates
UPDATE_TIME = 15*MINUTE

# RSS Polling
NUM_RSS_THREADS = 50 # until further testing
JOB_QUEUE_SIZE = 1000
CHECK_TIMESTAMP = False